apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: e6bzj07pr-go 
  janus-idp.io/tekton: e6bzj07pr-go
  backstage.io/kubernetes-id: e6bzj07pr-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e6bzj07pr-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml